spring:
  application:
    name: basic-board
  datasource:
    #   jdbc:mysql://localhost:3306/java_basic
    #   └─┬─┘ └─┬─┘   └───┬───┘ └┬┘ └───┬────┘
    #   프로토콜 DB종류     호스트   포트   DB이름
    # MySQL(서버)과 스프링부트는 "서로 다른 프로그램"이다.
    # 같은 컴퓨터에 있어도 남남이라, 함수 호출로는 못 부르고 "네트워크로 대화"해야 한다.
    # 그 대화 규약(약속)이 TCP이다. 이 URL은 "누구에게 어떻게 연결할지"를 적은 주소이다.

    # 왜 TCP인가?(신뢰성 있는 연결형 통신)
    # - TCP는 데이터를 보내기 전에 먼저 "연결을 수립"한다. (3-way handshake: SYN -> SYN/ACK -> ACK)
    # - 그 뒤엔 (a) 순서 보장 (b) 유실 시 재전송 (c) 도착 확인을 해준다 -> SQL/결과가 깨지거나 순서 꼬이면 안되므로 딱 맞다.

    # 그래서 "커넥션 풀(HikariCP)"이 필요하다. * 로그에서 보이던 HikariPool
    # - 위 handshake + 인증은 매번 느리고 비싸다. 요청마다 새로 연결하면 성능이 크게 떨어진다.
    # - 그래서 앱은 시작할 때 TCP 연결 여러 개를 미리 만들어 '풀(pool)'에 담아두고 재사용한다.

    # localhost (IP주소)
    # - localhost는 127.0.0.1, 즉 "내 컴퓨터 자신"을 가리키는 특별한 주소
    # 3306 (Port)
    # - 한 컴퓨터엔 프로그램이 많이 떠 있다. IP만으로는 특정지을 수 없다.
    # - 포트는 "그 컴퓨터 만의 창구 번호"이다. OS가 들어온 데이터를 포트 번호로 보고 알맞은 프로세스에게 전달한다.

    # 소켓(socket)과 연결(connection)
    # - "내쪽 IP:port"와 "상대 IP:port"한 쌍이 이어지면 하나의 '연결(connection)'이 된다.
    # - 프로그램은 이 연결의 양 끝의 '소켓'이라는 창구로 다룬다.
    url: jdbc:mysql://localhost:3306/java_basic_2?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB # 파일 1개 최대 크기(기본 1MB여서 쉽게 초과됨)
      max-request-size: 10MB # 요청 전체 최대 크기

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true # 출력되는 SQL을 보기좋게 출력

# logging.level - "어느 패키지의 로그를 어느 레벨부터 보여줄지"정하는 스위치
# 패키지별로 다르게 줄 수 있다.
# - root : 모든 로그의 기본값, 스프링 부트 기본이 info라서 보통 그대로 둔다.
# - 우리 패키지만 debug로 낮추면, 스프링/하이버네이트 내부 로그는 조용한 채로
# 우리가 심은 log.debug까지 보인다 -> 개발할 때 편함
# - 운영 배포 시엔 우리 패키지도 info로 올린다.(debug는 양이 많아 디스크/성능에 부담)
logging:
  level:
    roof: info
    com.example.basic_board: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html

file:
  upload-dir: ./uploads