spring:
  application:
    name: sign-up
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic_2?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  upload-dir: ./uploads